export const destinations = [
    {
        id: 'rameshwaram',
        name: 'Rameshwaram',
        state: 'Tamil Nadu',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80',
        description: 'One of the four sacred dhams of Hinduism, home to the magnificent Ramanathaswamy Temple with 1212 pillared corridors.',
        rating: 4.9,
        reviews: 2840,
        bestTime: 'October – April',
        duration: '2–3 days',
        highlights: ['Ramanathaswamy Temple', 'Agni Teertham', 'Dhanushkodi', 'Pamban Bridge'],
        category: 'Divine',
        price: 8999,
        temples: ['Ramanathaswamy Temple', 'Gandhamadana Parvatham', 'Kothandaramaswamy Temple'],
        hotels: ['Hotel Sea View', 'Rameshwaram Residency', 'TTDC Beach Hotel'],
        travelTips: [
            'Carry light cotton clothes – it gets very hot',
            'Visit temples early morning to avoid crowds',
            'The 22 theerthams (wells) ritual is a must-do',
        ],
    },
    {
        id: 'madurai',
        name: 'Madurai',
        state: 'Tamil Nadu',
        image: '/images/madurai.jpg',
        description: 'The cultural capital of Tamil Nadu, home to the iconic Meenakshi Amman Temple – one of India\'s greatest architectural wonders.',
        rating: 4.8,
        reviews: 3621,
        bestTime: 'October – March',
        duration: '2 days',
        highlights: ['Meenakshi Temple', 'Thirumalai Nayak Palace', 'Gandhi Memorial Museum', 'Vaigai River'],
        category: 'Heritage',
        price: 6999,
        temples: ['Meenakshi Amman Temple', 'Koodal Azhagar Temple', 'Thiruparankundram Temple'],
        hotels: ['Heritage Madurai', 'Taj Gateway', 'Noor Us Sabah Palace'],
        travelTips: [
            'Attend the grand evening aarti at Meenakshi Temple',
            'Try kari dosai and jigarthanda – local specialties',
            'Avoid midday visits to temples in summer',
        ],
    },
    {
        id: 'varanasi',
        name: 'Varanasi',
        state: 'Uttar Pradesh',
        image: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80',
        description: 'The spiritual capital of India and one of the world\'s oldest cities. The Ganga Aarti at Dashashwamedh Ghat is a transcendental experience.',
        rating: 4.9,
        reviews: 5210,
        bestTime: 'October – March',
        duration: '3–4 days',
        highlights: ['Dashashwamedh Ghat', 'Kashi Vishwanath', 'Sarnath', 'Evening Ganga Aarti'],
        category: 'Spiritual',
        price: 11999,
        temples: ['Kashi Vishwanath Temple', 'Sankat Mochan Temple', 'Durga Temple'],
        hotels: ['BrijRama Palace', 'Taj Ganges', 'Hotel Surya'],
        travelTips: [
            'Wake up at 5 AM for the magical sunrise boat ride',
            'Ganga Aarti at evening is a must-watch spectacle',
            'Respect the sacred nature of the ghats',
        ],
    },
    {
        id: 'tirupati',
        name: 'Tirupati',
        state: 'Andhra Pradesh',
        image: '/images/tirupati.jpg',
        description: 'Tirumala Tirupati Devasthanams – the richest and most visited temple in the world with over 50,000 pilgrims daily.',
        rating: 4.9,
        reviews: 7834,
        bestTime: 'September – February',
        duration: '2–3 days',
        highlights: ['Tirumala Temple', 'Tiruchanur Temple', 'Chandragiri Fort', 'Kapila Teertham'],
        category: 'Divine',
        price: 9499,
        temples: ['Sri Venkateswara Temple', 'Tiruchanur Padmavathi Temple', 'Govindarajaswamy Temple'],
        hotels: ['Fortune Select Grand Ridge', 'Ikshvakus Hotel', 'TTD Guest House'],
        travelTips: [
            'Book darshan tickets online well in advance via TTD portal',
            'Be prepared for long queues – carry snacks and water',
            'Laddu prasad is world-famous – buy it from the temple counter',
        ],
    },
    {
        id: 'kanyakumari',
        name: 'Kanyakumari',
        state: 'Tamil Nadu',
        image: '/images/kanyakumari.jpg',
        description: 'The southernmost tip of India where three seas meet. Home to the Vivekananda Rock Memorial and Thiruvalluvar Statue.',
        rating: 4.7,
        reviews: 2198,
        bestTime: 'October – February',
        duration: '1–2 days',
        highlights: ['Vivekananda Rock', 'Thiruvalluvar Statue', 'Sunrise/Sunset Point', 'Kumari Amman Temple'],
        category: 'Heritage',
        price: 7499,
        temples: ['Kumari Amman Temple', 'Thanumalayan Temple', 'Nagaraja Temple'],
        hotels: ['Sparsa Resort', 'Hotel Tamil Nadu', 'Seashore Hotel'],
        travelTips: [
            'Sunrise and sunset from the same point is a rare sight – plan accordingly',
            'Boat rides to Vivekananda Rock are an experience of a lifetime',
            'December–January for the best weather',
        ],
    },
];

export const packages = [
    {
        id: 'rameshwaram-3d',
        name: 'Rameshwaram Spiritual Tour',
        destination: 'Rameshwaram',
        duration: '3 Days / 2 Nights',
        price: 8999,
        originalPrice: 12999,
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80',
        rating: 4.9,
        reviews: 412,
        category: 'Budget',
        inclusions: ['Hotel (2 nights)', 'Breakfast daily', 'Temple guide', 'Local transport', 'Pamban Bridge visit'],
        highlights: ['Ramanathaswamy Temple darshan', '22 Theerthams ritual', 'Dhanushkodi beach', 'Agni Teertham'],
        hotelType: '3 Star',
        transport: 'AC Bus',
        groupSize: '10–20 people',
        badge: 'Best Seller',
    },
    {
        id: 'madurai-2d',
        name: 'Madurai Temple Yatra',
        destination: 'Madurai',
        duration: '2 Days / 1 Night',
        price: 6999,
        originalPrice: 9500,
        image: '/images/madurai.jpg',
        rating: 4.8,
        reviews: 287,
        category: 'Budget',
        inclusions: ['Hotel (1 night)', 'Breakfast', 'Temple guide', 'City transport', 'Evening aarti'],
        highlights: ['Meenakshi Amman Temple', 'Thirumalai Nayak Palace', 'Gandamadana Parvatham', 'Vaigai River'],
        hotelType: '3 Star',
        transport: 'AC Traveller',
        groupSize: '8–15 people',
        badge: 'Popular',
    },
    {
        id: 'varanasi-4d',
        name: 'Kashi Vishwanath Pilgrimage',
        destination: 'Varanasi',
        duration: '4 Days / 3 Nights',
        price: 14999,
        originalPrice: 19999,
        image: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80',
        rating: 4.9,
        reviews: 634,
        category: 'Premium',
        inclusions: ['Hotel (3 nights)', 'All meals', 'Boat ride', 'Temple guide', 'Private car', 'Sarnath visit'],
        highlights: ['Kashi Vishwanath darshan', 'Ganga Aarti ceremony', 'Sunrise boat ride', 'Sarnath Buddhist site'],
        hotelType: '4 Star',
        transport: 'Private AC Car',
        groupSize: '4–8 people',
        badge: 'Premium',
    },
    {
        id: 'south-circuit-7d',
        name: 'South India Sacred Circuit',
        destination: 'Multi-destination',
        duration: '7 Days / 6 Nights',
        price: 32999,
        originalPrice: 45000,
        image: '/images/kanyakumari.jpg',
        rating: 4.9,
        reviews: 198,
        category: 'Luxury',
        inclusions: ['5-star hotels', 'All meals', 'Flights', 'Private guide', 'VIP darshan', 'Resort stay'],
        highlights: ['Tirupati → Madurai → Rameshwaram → Kanyakumari', 'All major temples', 'Beach visit', 'Sunset at Kanyakumari'],
        hotelType: '5 Star',
        transport: 'Private Luxury Car + Flight',
        groupSize: '2–6 people',
        badge: 'Luxury',
    },
    {
        id: 'tirupati-2d',
        name: 'Tirupati Balaji Darshan',
        destination: 'Tirupati',
        duration: '2 Days / 1 Night',
        price: 9499,
        originalPrice: 13000,
        image: '/images/tirupati.jpg',
        rating: 4.9,
        reviews: 856,
        category: 'Premium',
        inclusions: ['Hotel (1 night)', 'Darshan ticket included', 'Prasad', 'Transport to hills', 'Guide'],
        highlights: ['Sri Venkateswara darshan', 'Tiruchanur temple', 'Laddu prasad', 'Chandragiri fort'],
        hotelType: '4 Star',
        transport: 'AC Bus + Ropeway',
        groupSize: '6–12 people',
        badge: 'New',
    },
    {
        id: 'kanyakumari-2d',
        name: 'Kanyakumari Sunrise Tour',
        destination: 'Kanyakumari',
        duration: '2 Days / 1 Night',
        price: 7499,
        originalPrice: 10000,
        image: '/images/kanyakumari.jpg',
        rating: 4.7,
        reviews: 342,
        category: 'Budget',
        inclusions: ['Hotel (1 night)', 'Breakfast', 'Boat ride', 'Local guide', 'Sunset viewing'],
        highlights: ['Vivekananda Rock', 'Sunrise & sunset', 'Kumari Amman Temple', 'Thiruvalluvar Statue'],
        hotelType: '3 Star',
        transport: 'AC Traveller',
        groupSize: '10–20 people',
        badge: 'Budget Friendly',
    },
];

export const reviews = [
    {
        id: 1,
        name: 'Priya Sharma',
        location: 'Mumbai',
        avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
        rating: 5,
        destination: 'Rameshwaram',
        review: 'Absolutely divine experience! The AI trip planner created a perfect 3-day itinerary. The temple guide knew every ritual in detail. Ramanathaswamy Temple left me in tears. Will book again!',
        date: 'February 2025',
        package: 'Rameshwaram Spiritual Tour',
    },
    {
        id: 2,
        name: 'Rajesh Kumar',
        location: 'Bangalore',
        avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
        rating: 5,
        destination: 'Varanasi',
        review: 'The Ganga Aarti at Dashashwamedh Ghat is something I\'ll carry in my heart forever. Ramayan Tours managed everything flawlessly – hotel, temples, boat ride. Exceptional service!',
        date: 'January 2025',
        package: 'Kashi Vishwanath Pilgrimage',
    },
    {
        id: 3,
        name: 'Ananya Nair',
        location: 'Chennai',
        avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
        rating: 5,
        destination: 'Madurai',
        review: 'Meenakshi Temple in the evening light – breathtaking! The AI suggested Jigarthanda and I was hooked. Accommodation was clean, guide was knowledgeable. 10/10!',
        date: 'December 2024',
        package: 'Madurai Temple Yatra',
    },
    {
        id: 4,
        name: 'Suresh Patel',
        location: 'Ahmedabad',
        avatar: 'https://randomuser.me/api/portraits/men/75.jpg',
        rating: 5,
        destination: 'Tirupati',
        review: 'Got VIP darshan tickets sorted by the team – no waiting in long lines! The whole Tirupati experience was spiritual and well-organized. Worth every rupee spent!',
        date: 'November 2024',
        package: 'Tirupati Balaji Darshan',
    },
    {
        id: 5,
        name: 'Meera Krishnan',
        location: 'Hyderabad',
        avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
        rating: 5,
        destination: 'South Circuit',
        review: 'The 7-day South India Sacred Circuit was life-changing. From Tirupati to Kanyakumari – every destination, every moment was perfectly planned. The AI itinerary was spot on!',
        date: 'October 2024',
        package: 'South India Sacred Circuit',
    },
    {
        id: 6,
        name: 'Arjun Menon',
        location: 'Kochi',
        avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
        rating: 4,
        destination: 'Kanyakumari',
        review: 'Watching the sunrise where three oceans meet – absolutely unforgettable. The boat to Vivekananda Rock was arranged perfectly. Would have loved a longer stay but overall wonderful!',
        date: 'September 2024',
        package: 'Kanyakumari Sunrise Tour',
    },
];

export const blogPosts = [
    {
        id: 1,
        title: '22 Theerthams of Rameshwaram: A Complete Guide',
        excerpt: 'Discover the spiritual significance and rituals of the 22 sacred water bodies inside Ramanathaswamy Temple...',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80',
        category: 'Temple Guide',
        author: 'Pandit Ramakrishna',
        date: 'March 3, 2025',
        readTime: '8 min read',
        slug: '22-theerthams-rameshwaram-guide',
    },
    {
        id: 2,
        title: 'Ganga Aarti: Best Ghats to Experience in Varanasi',
        excerpt: 'A detailed guide to the most spectacular evening Ganga Aarti ceremonies and the best viewing spots at Varanasi ghats...',
        image: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80',
        category: 'Travel Guide',
        author: 'Kavya Sharma',
        date: 'February 18, 2025',
        readTime: '6 min read',
        slug: 'ganga-aarti-varanasi-guide',
    },
    {
        id: 3,
        title: 'How AI is Revolutionizing Pilgrimage Planning in India',
        excerpt: 'From personalized itineraries to temple timing alerts, AI is making sacred journeys more accessible and meaningful...',
        image: 'https://images.unsplash.com/photo-1620766182762-a11060be91e7?w=800&q=80',
        category: 'Technology',
        author: 'Amit Verma',
        date: 'February 5, 2025',
        readTime: '5 min read',
        slug: 'ai-pilgrimage-planning-india',
    },
    {
        id: 4,
        title: 'Best Time to Visit Meenakshi Temple: Season Guide',
        excerpt: 'A month-by-month breakdown of festivals, weather, and crowd levels at the magnificent Meenakshi Amman Temple...',
        image: 'https://images.unsplash.com/photo-1624461050280-c290d4157cd1?w=800&q=80',
        category: 'Temple Guide',
        author: 'Lakshmi Devi',
        date: 'January 20, 2025',
        readTime: '7 min read',
        slug: 'best-time-meenakshi-temple',
    },
];

export const stats = [
    { label: 'Happy Pilgrims', value: 50000, suffix: '+' },
    { label: 'Temples Covered', value: 200, suffix: '+' },
    { label: 'Tour Packages', value: 85, suffix: '+' },
    { label: 'Years of Experience', value: 12, suffix: '+' },
];

export const taxiPackages = [
    {
        id: 'rameshwaram-1d',
        name: 'Rameswaram One Day Tour',
        price: '₹3,200',
        perPerson: 'For 2 Persons',
        pickup: 'Rameshwaram',
        image: '/images/taxi/rameshwaram.png',
        duration: '1 Day',
    },
    {
        id: 'rameshwaram-2d',
        name: 'Rameshwaram Two Days Tour',
        price: 'Call for Price',
        perPerson: 'Starting from 2 Persons',
        pickup: 'Mandapam / Rameshwaram',
        image: '/images/taxi/rameshwaram.png',
        duration: '2 Days',
    },
    {
        id: 'madurai-ramesh-kanya-4d',
        name: 'Madurai - Rameshwaram - Kanyakumari',
        price: 'Call for Price',
        perPerson: 'For 2 Persons',
        pickup: 'Madurai',
        image: '/images/taxi/madurai.png',
        duration: '3 Nights / 4 Days',
    },
    {
        id: 'ramesh-kanya-trivandrum-2d',
        name: 'Rameshwaram - Kanyakumari - Trivandrum',
        price: 'Call for Price',
        perPerson: 'For 2 Persons',
        pickup: 'Rameshwaram',
        image: '/images/taxi/kanyakumari.png',
        duration: '2 Nights / 3 Days',
    },
    {
        id: 'ramesh-madurai-kanya-trivandrum-4d',
        name: 'Rameshwaram - Madurai - Kanyakumari - Trivandrum',
        price: 'Call for Price',
        perPerson: 'For 2 Persons',
        pickup: 'Rameshwaram',
        image: '/images/taxi/kanyakumari.png',
        duration: '3 Nights / 4 Days',
    },
    {
        id: 'madurai-ramesh-kanya-trivandrum-4d-drop',
        name: 'Madurai - Rameshwaram - Kanyakumari - Trivandrum Drop',
        price: '₹27,500',
        perPerson: 'For 2 Persons',
        pickup: 'Madurai',
        image: '/images/taxi/madurai.png',
        duration: '3 Nights / 4 Days',
    },
    {
        id: 'trivandrum-kanya-ramesh-madurai-4d',
        name: 'Trivandrum - Kanyakumari - Rameshwaram - Madurai Drop',
        price: '₹32,300',
        perPerson: 'For 2 Persons',
        pickup: 'Trivandrum (Kerala)',
        image: '/images/taxi/kerala.png',
        duration: '3 Nights / 4 Days',
    },
    {
        id: 'ramesh-madurai-kodai-ooty-9d',
        name: 'Rameshwaram - Madurai - Kodaikanal - Ooty',
        price: 'Call for Price',
        perPerson: 'Customized Tour',
        pickup: 'Madurai',
        image: '/images/taxi/madurai.png',
        duration: '8 Nights / 9 Days',
    },
];
